#!/usr/bin/env python3
"""Generate assets/css/tokens.css and assets/js/tailwind-config.js from design/DESIGN.md.

The dark palette is the Stitch design system verbatim. The light palette below is ours: Stitch only
drew a dark theme. Colours become CSS variables (space-separated RGB, so Tailwind opacity modifiers
like bg-surface/90 keep working) and the theme is switched with <html data-theme="light|dark">.
Run:  python3 tools/gen_tokens.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
front = (ROOT / "design" / "DESIGN.md").read_text().split("---")[1]
colors_block = front.split("colors:")[1].split("typography:")[0]
dark = dict(re.findall(r"^\s+([a-z0-9-]+): '(#[0-9a-fA-F]{6})'", colors_block, re.M))

# Only the tokens that differ; every other token keeps its dark value in both themes.
light = {
    "surface": "#f7f8fa", "surface-dim": "#e6e9ed", "surface-bright": "#ffffff", "background": "#f7f8fa",
    "surface-container-lowest": "#ffffff", "surface-container-low": "#f1f3f6", "surface-container": "#e9ecf0",
    "surface-container-high": "#e0e4ea", "surface-container-highest": "#d6dbe2", "surface-variant": "#d6dbe2",
    "on-surface": "#14181d", "on-background": "#14181d", "on-surface-variant": "#4f4538",
    "inverse-surface": "#14181d", "inverse-on-surface": "#f7f8fa",
    "outline": "#7a6a58", "outline-variant": "#cdbfae", "surface-tint": "#855300",
    "primary": "#855300", "on-primary": "#ffffff", "inverse-primary": "#ffc174",
    "primary-container": "#f59e0b", "on-primary-container": "#2a1700",
    "secondary": "#9c3a0b", "on-secondary": "#ffffff", "secondary-container": "#f66018",
    "on-secondary-container": "#2a0a00",
    "tertiary": "#00628a", "on-tertiary": "#ffffff", "tertiary-container": "#38bdf8",
    "on-tertiary-container": "#00293a",
    "error": "#ba1a1a", "on-error": "#ffffff", "error-container": "#ffdad6", "on-error-container": "#410002",
}


def rgb(h):
    h = h.lstrip("#")
    return " ".join(str(int(h[i:i + 2], 16)) for i in (0, 2, 4))


css = ["/* GENERATED by tools/gen_tokens.py from design/DESIGN.md -- do not edit by hand. */",
       ":root, :root[data-theme=\"dark\"] {", "  color-scheme: dark;"]
css += [f"  --c-{k}: {rgb(v)};" for k, v in dark.items()]
css += ["}", ":root[data-theme=\"light\"] {", "  color-scheme: light;"]
css += [f"  --c-{k}: {rgb(v)};" for k, v in light.items()]
css += ["}", ""]
(ROOT / "assets/css/tokens.css").write_text("\n".join(css))

cfg = {
    "colors": {k: f"rgb(var(--c-{k}) / <alpha-value>)" for k in dark},
    "borderRadius": {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    "spacing": {"space-xs": "0.25rem", "space-sm": "0.5rem", "space-md": "0.75rem", "space-lg": "1.25rem",
                "space-xl": "2rem", "gutter": "1rem", "margin": "1.25rem"},
    "fontFamily": {k: [f] for k, f in {
        "label-caps": "JetBrains Mono", "mono-data-sm": "JetBrains Mono", "mono-data-md": "JetBrains Mono",
        "mono-data-lg": "JetBrains Mono", "display": "Inter", "headline-lg": "Inter",
        "headline-lg-mobile": "Inter", "headline-md": "Inter", "headline-sm": "Inter", "body-lg": "Inter",
        "body-md": "Inter", "body-sm": "Inter"}.items()},
    "fontSize": {
        "label-caps": ["10px", {"lineHeight": "12px", "letterSpacing": "0.08em", "fontWeight": "600"}],
        "mono-data-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "400"}],
        "mono-data-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0em", "fontWeight": "400"}],
        "mono-data-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "display": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600"}],
        "headline-lg-mobile": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-md": ["18px", {"lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-sm": ["15px", {"lineHeight": "20px", "letterSpacing": "-0.005em", "fontWeight": "600"}],
        "body-lg": ["15px", {"lineHeight": "22px", "fontWeight": "400"}],
        "body-md": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "body-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}]},
}
js = ("// GENERATED by tools/gen_tokens.py -- do not edit by hand.\n"
      "tailwind.config = { theme: { extend: " + json.dumps(cfg, indent=2) + " } };\n")
(ROOT / "assets/js/tailwind-config.js").write_text(js)
print(f"{len(dark)} dark tokens, {len(light)} light overrides")
